name: CI

on:
    push:
    pull_request:

jobs:
    build:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Pull images
              run: docker-compose pull
            - name: Docker build
              run: docker-compose build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} 
            - name: Docker up
              run: docker-compose up -d
